# Generated by Django 4.2.5 on 2023-10-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework2_shop_app', '0002_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='image',
        ),
    ]
